"""operations and events

Revision ID: 891dd905419f
Revises: 
Create Date: 2026-07-16 20:51:50.801722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891dd905419f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('operation_id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_table('operation_events',
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ),
    sa.PrimaryKeyConstraint('operation_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_events')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
