"""dispatch scheduling columns

Revision ID: cba79cffe010
Revises: 891dd905419f
Create Date: 2026-07-17 00:43:22.171414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba79cffe010'
down_revision: Union[str, Sequence[str], None] = '891dd905419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('operations', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'next_attempt_at')
    op.drop_column('operations', 'attempt_count')
    # ### end Alembic commands ###
